version: "3"
services:
    db:
        container_name: bookshelfdb
        image: mysql
        ports:
            - "3302:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"