FROM python

RUN pip install -r requirements.txt

WORKDIR C:\Users\gusta\Documents\GitHub\Bookshelf_project\src

COPY C:\Users\gusta\Documents\GitHub\Bookshelf_project\src

COPY C:\Users\gusta\Documents\OG

COPY C:\Users\gusta\Documents\USE

CMD python main.py